trigger: none
pool: agentpool_babu
stages:
  - stage:
    displayName: terraform-tool
    jobs:
        job: terraform_job
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendAzureRmOverrideSubscriptionID: 'b3922ee1-b132-4af3-a9e7-52bfedb4da65'
            backendAzureRmResourceGroupName: 'resource_group_new'
            backendAzureRmStorageAccountName: 'storageaccountfeb'
            backendAzureRmContainerName: 'storageconnew'
            backendAzureRmKey: 'yaml_pipline'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'service_connection_name'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'service_connection_name'

